### ISSUE TITLE
请问我的每一个向量都是128D的人脸特征向量，如何添加进IndexFlatL2构建索引呢？ 

### ISSUE THREAD

**Issue by PaulX1029** [luojinlongjjj/android-faiss#4]
初次在android设备上使用faiss，首先感谢您所做的编译工作，现在我想使用faiss做人脸识别搜索，如何将128D的人脸特征向量构建索引呢？谢谢！
![image](https://user-images.githubusercontent.com/77143808/173523590-9eb8a7d9-eca2-4bed-b29f-a6e0eec284fa.png)

**Comment by PaulX1029** [comment]
faiss_feas数组存储了若干人脸的特征向量，每一行有128列，就是128个特征向量，这样该如何去构建索引？

**Comment by luojinlongjjj** [comment]
添加单个特征  要求faiss_feas[i]中的内存连续
faiss_index->add(1,faiss_feas[i])

**Comment by soham24** [comment]
@PaulX1029 were you able to do that ?

**Comment by PaulX1029** [comment]
@soham24  I succeeded

**Comment by soham24** [comment]
Do you have any reference code
