### ISSUE TITLE
遇到的问题

### ISSUE THREAD

**Issue by jymsq** [luojinlongjjj/android-faiss#6]
Error: 'f' failed: could not open /sdcard/tmp/1.index for writing: No such file or directory
terminating with uncaught exception of type faiss::FaissException: Error in faiss::(anonymous namespace)::FileIOWriter::FileIOWriter(const char *) at D:/githubDownloads/android-faiss/app/src/main/cpp/source/faiss/index_io.cpp:173: Error: 'f' failed: could not open /sdcard/tmp/1.index for writing: No such file or directory

**Comment by luojinlongjjj** [comment]
看上去是文件路径权限的问题
1.demo没有写外部存储的授权代码  需要手动补充下
2.如果android版本超过11  应该不能写在外部存储了  可以把/sdcard/tmp/1.index  改成app的沙盒路径
具体根据代码结局 报错与faiss无关

**Comment by jymsq** [comment]
感谢，问题已经解决，android版本的问题

**Comment by jymsq** [comment]
项目能够跑通但是不知道如何去使用这个库啊，在MainActivity下只暴露了一个stringFromJNI方法，请教一下怎么用

**Comment by luojinlongjjj** [comment]
这个你要学习下faiss的用法   可以去官网或者参考其它博主的使用
https://blog.csdn.net/LuohenYJ/article/details/125897842

**Comment by jymsq** [comment]
我知道faiss在python语言中如何使用，但是如果是想在android环境下使用，用java代码又如何编写呢（主要不知道从何入手），您这个项目目的不是为了在android开发环境下也能够使用faiss库吗

**Comment by luojinlongjjj** [comment]
参考下 native-lib.cpp  用c++写  通过jni给java用
我已经编译了静态库和动态库  你可以通过头文件使用 或者重新编

**Comment by jymsq** [comment]
好的感谢
